fos_ck_editor:
    configs:
        main_config:
            toolbar:
                - {
                      name: "styles",
                      items:
                          [
                              "Bold",
                              "Italic",
                              "Underline",
                              "Strike",
                              "Blockquote",
                              "-",
                              "RemoveFormat",
                              "-",
                              "NumberedList",
                              "BulletedList",
                              "-",
                              "Outdent",
                              "Indent",
                              "-",                              
                              "Image",
                              "Link",
                              "HorizontalRule",
                              "PageBreak",
                              "-",
                              "JustifyLeft",
                              "JustifyCenter",
                              "JustifyRight",
                              "JustifyBlock",
                              "-",   
                              "Format",
                              "Font",
                              "FontSize",
                              "-",
                              "TextColor",
                              "BGColor",
                              "Scayt",
                              "Maximize"                                                            
                          ],                          
                  }
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
                 
            
